name: PR Comment Notifier

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  comment:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write  # ⬅️ Important!

    steps:
      - name: Add a comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          COMMENT_BODY="👋 Hi @${{ github.event.pull_request.user.login }}, thanks for your PR! We're reviewing it now."

          curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
            -d "{\"body\": \"$COMMENT_BODY\"}"
